version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: example
    env_file: .env
    networks:
      - spring-network
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 2s
      retries: 100

  app:
    depends_on:
      db:
        condition: service_started
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      MYSQL_HOST: db
    networks:
      - spring-network
    restart: always

networks:
  spring-network:

volumes:
  mysql-data:
