spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/board
    username: user
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60